-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2023-05-19 11:19:31 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE TB_CRIMES
  (
    id       INTEGER NOT NULL ,
    nm_crime VARCHAR2 (30 CHAR) NOT NULL ,
    ds_crime VARCHAR2 (150 CHAR)
  ) ;
ALTER TABLE TB_CRIMES ADD CONSTRAINT TB_CRIMES_PK PRIMARY KEY ( id ) ;


CREATE TABLE TB_CRIMES_COMETIDOS
  (
    TB_CRIMINOSOS_id INTEGER NOT NULL ,
    TB_CRIMES_id     INTEGER NOT NULL
  ) ;
ALTER TABLE TB_CRIMES_COMETIDOS ADD CONSTRAINT TB_CRIMES_COMETIDOS_PK PRIMARY KEY ( TB_CRIMINOSOS_id, TB_CRIMES_id ) ;


CREATE TABLE TB_CRIMINOSOS
  (
    id            INTEGER NOT NULL ,
    nm_criminoso  VARCHAR2 (130 CHAR) NOT NULL ,
    dt_nascimento DATE NOT NULL ,
    genero        VARCHAR2 (1 CHAR) NOT NULL ,
    altura FLOAT (2) NOT NULL ,
    peso FLOAT (1) NOT NULL ,
    organizacao   VARCHAR2 (10 CHAR) NOT NULL ,
    nacionalidade VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE TB_CRIMINOSOS ADD CONSTRAINT TB_CRIMINOSOS_PK PRIMARY KEY ( id ) ;


ALTER TABLE TB_CRIMES_COMETIDOS ADD CONSTRAINT FK_ASS_1 FOREIGN KEY ( TB_CRIMINOSOS_id ) REFERENCES TB_CRIMINOSOS ( id ) ;

ALTER TABLE TB_CRIMES_COMETIDOS ADD CONSTRAINT FK_ASS_2 FOREIGN KEY ( TB_CRIMES_id ) REFERENCES TB_CRIMES ( id ) ;

CREATE SEQUENCE TB_CRIMES_id_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER TB_CRIMES_id_TRG BEFORE
  INSERT ON TB_CRIMES FOR EACH ROW WHEN (NEW.id IS NULL) BEGIN :NEW.id := TB_CRIMES_id_SEQ.NEXTVAL;
END;

CREATE SEQUENCE TB_CRIMINOSOS_id_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER TB_CRIMINOSOS_id_TRG BEFORE
  INSERT ON TB_CRIMINOSOS FOR EACH ROW WHEN (NEW.id IS NULL) BEGIN :NEW.id := TB_CRIMINOSOS_id_SEQ.NEXTVAL;
END;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           2
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          2
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
